[book]
authors = ["Jacob Hummer"]
language = "en"
multilingual = false
src = "src"
title = "CMake by Example"

[output.html]
git-repository-url = "https://github.com/jcbhmr/cmakebyexample.jcbhmr.com"
edit-url-template = "https://github.com/jcbhmr/cmakebyexample.jcbhmr.com/edit/main/{path}"

# https://github.com/FauconFan/mdbook-cmdrun
[preprocessor.cmdrun]
